## ImpactTypes.gd
## Data structures, constants, and enums for the universal collision & impact solver.
class_name ImpactTypes
extends RefCounted

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

## Physical form of the impact or attack delivery.
enum Form {
	BLUNT      = 0,  ## Hammers, fists, falling rocks, blunt debris (high momentum, broad area)
	PIERCE     = 1,  ## Claws, fangs, needles, arrows, spears (extreme localized pressure)
	SLASH      = 2,  ## Blades, sharp claws, shears (shearing along surface)
	PROJECTILE = 3,  ## Bullets, high-speed ballistic debris (extreme velocity)
	CRUSH      = 4,  ## Compression, hydraulic traps, boulders rolling over targets
	SPLASH     = 5,  ## Liquid mass or explosive concussive wave
}

## Primary physical outcome of the collision.
enum Outcome {
	DEFLECTED      = 0,  ## Striker bounced off with minimal/no permanent damage to target
	PENETRATED     = 1,  ## Striker pierced or sheared through target surface
	SHATTERED      = 2,  ## High stress exceeded brittle yield threshold, crumbling into debris
	DEFORMED       = 3,  ## Material absorbed energy through ductile / plastic deformation
	ABSORBED       = 4,  ## Energy fully dissipated by viscous, elastic, or compliant material
	SPLASHED       = 5,  ## Fluid mass displaced or splashed on impact
	PASSED_THROUGH = 6,  ## Striker passed through medium (gas/vapor) with negligible drag
}

# ---------------------------------------------------------------------------
# Typed Data Structures
# ---------------------------------------------------------------------------

## Parameters characterizing the striking entity/material in a collision.
class ImpactParams extends RefCounted:
	## Total kinetic energy of the impact in Joules.
	## If not specified, can be calculated from mass and velocity.
	var kinetic_energy: float = 100.0

	## Relative velocity vector (in m/s or tiles/sec).
	var velocity: Vector2 = Vector2.ZERO

	## Mass of the striker in kilograms (default 1.0 kg).
	var mass: float = 1.0

	## Effective contact surface area in square meters.
	## Fine point (needle, claw tip): 0.00005 m2
	## Blade edge (sword, slash claw): 0.0002 m2
	## Fist / blunt club / small stone: 0.01 m2
	## Large boulder / shield / wall: 0.1 m2
	var contact_area: float = 0.0001

	## The attack / impact form.
	var form: int = Form.BLUNT

	## Temperature of the striking body in Celsius (e.g. flaming sword, red-hot projectile).
	var temperature_c: float = 20.0

	## Optional custom striker sharpness multiplier (1.0 = standard, >1.0 = razor).
	var sharpness: float = 1.0

	## Convenience factory creating params from mass and velocity.
	static func from_motion(p_mass: float, p_velocity: Vector2, p_area: float = 0.0001, p_form: int = Form.BLUNT) -> ImpactParams:
		var params = ImpactParams.new()
		params.mass = maxf(0.001, p_mass)
		params.velocity = p_velocity
		var speed: float = p_velocity.length()
		params.kinetic_energy = 0.5 * params.mass * speed * speed
		params.contact_area = maxf(0.000001, p_area)
		params.form = p_form
		return params

## Comprehensive diagnostic and mechanical result of an impact.
class ImpactResult extends RefCounted:
	## High-level physical outcome enum.
	var outcome: int = Outcome.DEFLECTED

	## Structural / yield damage inflicted upon the target (in MPa / structural HP).
	var damage_to_target: float = 0.0

	## Wear, chipping, or deformation inflicted upon the striker.
	var damage_to_striker: float = 0.0

	## True if target structural integrity / yield strength dropped to 0 (broken/destroyed).
	var target_fractured: bool = false

	## True if striker structural integrity / yield strength dropped to 0 (shattered/chipped).
	var striker_fractured: bool = false

	## Estimated penetration depth (in meters, or percentage 0.0 to 1.0 for thin barriers).
	var penetration_depth: float = 0.0

	## Residual rebound velocity vector of the striker after impact.
	var rebound_velocity: Vector2 = Vector2.ZERO

	## Residual kinetic energy of the rebound in Joules.
	var rebound_energy: float = 0.0

	## Energy absorbed into plastic deformation, micro-fracturing, and sound (Joules).
	var energy_absorbed: float = 0.0

	## Temperature increase in Celsius produced by friction and deformation.
	var heat_generated_c: float = 0.0

	## True if high-friction contact between hard surfaces produced incandescent sparks.
	var sparks_produced: bool = false

	## True if heat or sparks caused flammable material to ignite.
	var ignition_occurred: bool = false

	## Acoustic loudness generated by the impact (0.0 to 1.0, ready for SignalSystem).
	var sound_loudness: float = 0.0

	## Contaminants, liquids, or chemicals transferred between striker and target.
	## Keys: "toxicity", "corrosion", "moisture", "material_id"
	var contaminants_transferred: Dictionary = {}

	## Material archetype ID of debris created if fracture occurred (-1 if none).
	var debris_material_id: int = -1

	## Human-readable summary of the collision physics.
	var summary: String = ""
